### ISSUE TITLE
Add tabulate python package to Blackmesh

### ISSUE THREAD

**Issue by DanielJWood** [energyapps/egallon-serve#3]
Per our email conversation, we need to install the "tabulate" python package in order for egallon and utilities to run correctly. Per your email, the following error resulted from running diagnostic.py.

```
Traceback (most recent call last):
  File "egallon/diagnostic.py", line 6, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate
Null message body; hope that's ok
Traceback (most recent call last):
  File "utilities/diagnostic.py", line 6, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate
Null message body; hope that's ok
```

This should cause the diagnostic python script to render something similar to this for eGallon:

```
Date diagnostic generated: June 04, 2016

Oil Price Statistics
Date Oil Data produced: 20160530
The minimum: $2.09 | Region: GC
The maximum: $2.81 | Region: CA
The average: $2.31865384615

Egallon Price Statistics
Date Electricity Data produced: 201603
The minimum: $0.83 | State: Louisiana
The maximum: $2.49 | State: Hawaii
The average: $1.19557692308

Differences
3 Smallest differences in Egallon and Oil Prices
1) Hawaii: $-0.06
2) Connecticut: $0.45
3) Massachusetts: $0.52

3 Largest differences in Egallon and Oil Prices
1) Washington: $1.74
2) Oregon: $1.48
3) North Dakota: $1.45

The average difference between oil price and egallon price: $1.12307692308
| state                |   oil |   egallon |   diff |
|:---------------------|------:|----------:|-------:|
| Alaska               |  2.43 |      1.82 |   0.61 |
| Alabama              |  2.09 |      1.1  |   0.99 |
| Arkansas             |  2.09 |      0.87 |   1.22 |
| Arizona              |  2.43 |      1.07 |   1.36 |
| California           |  2.81 |      1.61 |   1.2  |
| Colorado             |  2.24 |      1.03 |   1.21 |
| Connecticut          |  2.35 |      1.9  |   0.45 |
| District of Columbia |  2.35 |      1.2  |   1.15 |
| Delaware             |  2.35 |      1.22 |   1.13 |
| Florida              |  2.2  |      1.02 |   1.18 |
| Georgia              |  2.22 |      1.01 |   1.21 |
| Hawaii               |  2.43 |      2.49 |  -0.06 |
| Iowa                 |  2.34 |      1.05 |   1.29 |
| Idaho                |  2.32 |      0.89 |   1.43 |
| Illinois             |  2.34 |      1.14 |   1.2  |
| Indiana              |  2.34 |      1.02 |   1.32 |
| Kansas               |  2.34 |      1.2  |   1.14 |
| Kentucky             |  2.34 |      0.91 |   1.43 |
| Louisiana            |  2.09 |      0.83 |   1.26 |
| Massachusetts        |  2.32 |      1.8  |   0.52 |
| Maryland             |  2.35 |      1.31 |   1.04 |
| Maine                |  2.35 |      1.71 |   0.64 |
| Michigan             |  2.34 |      1.35 |   0.99 |
| Minnesota            |  2.25 |      1.11 |   1.14 |
| Missouri             |  2.34 |      0.91 |   1.43 |
| Mississippi          |  2.09 |      0.99 |   1.1  |
| Montana              |  2.32 |      0.99 |   1.33 |
| North Carolina       |  2.22 |      1.06 |   1.16 |
| North Dakota         |  2.34 |      0.89 |   1.45 |
| Nebraska             |  2.34 |      0.94 |   1.4  |
| New Hampshire        |  2.35 |      1.68 |   0.67 |
| New Jersey           |  2.35 |      1.42 |   0.93 |
| New Mexico           |  2.09 |      1.04 |   1.05 |
| Nevada               |  2.43 |      1.12 |   1.31 |
| New York             |  2.39 |      1.54 |   0.85 |
| Ohio                 |  2.45 |      1.13 |   1.32 |
| Oklahoma             |  2.34 |      0.93 |   1.41 |
| Oregon               |  2.43 |      0.95 |   1.48 |
| Pennsylvania         |  2.35 |      1.28 |   1.07 |
| Rhode Island         |  2.35 |      1.73 |   0.62 |
| South Carolina       |  2.22 |      1.17 |   1.05 |
| South Dakota         |  2.34 |      1    |   1.34 |
| Tennessee            |  2.34 |      0.91 |   1.43 |
| Texas                |  2.09 |      1.02 |   1.07 |
| US Average           |  2.34 |      1.14 |   1.2  |
| Utah                 |  2.32 |      0.97 |   1.35 |
| Virginia             |  2.22 |      1.02 |   1.2  |
| Vermont              |  2.35 |      1.56 |   0.79 |
| Washington           |  2.58 |      0.84 |   1.74 |
| Wisconsin            |  2.34 |      1.29 |   1.05 |
| West Virginia        |  2.22 |      1    |   1.22 |
| Wyoming              |  2.32 |      0.99 |   1.33 |

End of Diagnostic Script
```

This should cause the diagnostic python script to render something similar to this for utilities:

```
Date diagnostic generated: June 04, 2016

Utility Price Statistics
Date Electricity Data produced: 201603
The minimum: $9.14 c/kWh | State: Louisiana
The maximum: $27.35 c/kWh | State: Hawaii
The average: $13.1494230769 c/kWh

| state                |   electric |
|:---------------------|-----------:|
| Alaska               |      20.06 |
| Alabama              |      12.11 |
| Arkansas             |       9.62 |
| Arizona              |      11.75 |
| California           |      17.66 |
| Colorado             |      11.35 |
| Connecticut          |      20.84 |
| District of Columbia |      13.24 |
| Delaware             |      13.39 |
| Florida              |      11.24 |
| Georgia              |      11.14 |
| Hawaii               |      27.35 |
| Iowa                 |      11.5  |
| Idaho                |       9.8  |
| Illinois             |      12.56 |
| Indiana              |      11.21 |
| Kansas               |      13.17 |
| Kentucky             |      10.05 |
| Louisiana            |       9.14 |
| Massachusetts        |      19.84 |
| Maryland             |      14.36 |
| Maine                |      18.8  |
| Michigan             |      14.83 |
| Minnesota            |      12.23 |
| Missouri             |      10.06 |
| Mississippi          |      10.91 |
| Montana              |      10.92 |
| North Carolina       |      11.66 |
| North Dakota         |       9.82 |
| Nebraska             |      10.31 |
| New Hampshire        |      18.46 |
| New Jersey           |      15.58 |
| New Mexico           |      11.44 |
| Nevada               |      12.28 |
| New York             |      16.89 |
| Ohio                 |      12.47 |
| Oklahoma             |      10.24 |
| Oregon               |      10.42 |
| Pennsylvania         |      14.06 |
| Rhode Island         |      19.07 |
| South Carolina       |      12.86 |
| South Dakota         |      10.98 |
| Tennessee            |      10.01 |
| Texas                |      11.25 |
| US Average           |      12.58 |
| Utah                 |      10.67 |
| Virginia             |      11.18 |
| Vermont              |      17.11 |
| Washington           |       9.22 |
| Wisconsin            |      14.23 |
| West Virginia        |      11    |
| Wyoming              |      10.85 |

End of Diagnostic Script
```

**Comment by chaunceyt** [comment]
Ticket created to install python plugin on servers:
[#1494447] Install tabulate on all of the production web instances
